In [ ]:
pip install numpy

# numpy 주의사항
(매우 느려짐)
- for문 
- 행,열 추가

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a[11])

11


In [ ]:
# 마지막 원소 추출
print(a[len(a)-1])

print(a[-1])

11
11


In [ ]:
print(a[-2])

10


In [ ]:
# 마지막 두 원소 추출
print(a[10:])

print(a[-2:])

[10 11]
[10 11]


In [ ]:
# 마지막 두 원소의 합
print(sum(a[-2:]))

21


In [ ]:
# 끝에서 4개 원소의 합
a = np.arange(12)
print(np.sum(a[-4:]))

38


In [ ]:
# True = 1, False = 0
print(5*1)
print(5*True)
print(5*False)

5
5
0


In [ ]:
a = np.array([0,1,2,3,4,5])
#b = np.array([0,0,0,1,1,1])
b = np.array([False,False,False,True,True,True])

print(a*b)

[0 0 0 3 4 5]


In [ ]:
a = np.arange(12)

mask = a%2==0
print(a)
print(mask)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ True False  True False  True False  True False  True False  True False]


In [ ]:
a = np.arange(25).reshape(5,5)
mask = np.array([
               [1,1,1,1,1],
               [1,0,0,0,1],
               [1,0,0,0,1],
               [1,0,0,0,1],
               [1,1,1,1,1]
               ])
print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]
192


In [ ]:
# 아래의 2차원 데이터 생성해보기
'''
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
'''
a = np.arange(25).reshape(5,5)
print(a)
mask = np.ones_like(a)
mask[1:4,1:4]=0

print(mask)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# 행렬의 대각선 원소들의 합 구해보기
a = np.arange(25).reshape(5,5)
print(a)
mask = np.eye(5)

print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]
60.0


In [ ]:
a = [0,1,2,3,4]
print(a)

# 인덱스 3번에 원소 추가하기
# 데이터.insert(인덱스, 추가할 원소)
a.insert(3,99)
print(a)

[0, 1, 2, 3, 4]
[0, 1, 2, 99, 3, 4]


In [ ]:
a = np.arange(4)
print(a)
print(a.shape)

[0 1 2 3]
(4,)


In [ ]:
# a=np.arange(4)로 아래의 shape 만들기
'''
(4,1)
(1,4)
(2,2)
'''
a = np.arange(4)
print(a)

print(a.reshape(4,1).shape)
print(a.reshape(1,4).shape)
print(a.reshape(2,2).shape)

[0 1 2 3]
(4, 1)
(1, 4)
(2, 2)


- 차원 확장 (expand)
- 차원 축소 (squeeze)

In [ ]:
# 1차원의 확장
a = np.arange(4)
a = np.expand_dims(a,axis=0)
print(a)
print(a.shape)

a = np.arange(4)
a = np.expand_dims(a,axis=1)
print(a)
print(a.shape)


# 차원의 마지막 확장
a = np.arange(4)
a = np.expand_dims(a,axis=-1)
print(a)
print(a.shape)

[[0 1 2 3]]
(1, 4)
[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0]
 [1]
 [2]
 [3]]
(4, 1)


In [ ]:
# 2차원 확장
a = np.arange(6).reshape((2,3))
a = np.expand_dims(a,axis=0)
print(a)
print(a.shape)

a = np.arange(6).reshape((2,3))
a = np.expand_dims(a,axis=1)
print(a)
print(a.shape)

a = np.arange(6).reshape((2,3))
a = np.expand_dims(a,axis=2)
print(a)
print(a.shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


In [ ]:
# 차원 축소
a = np.arange(12).reshape((1,3,4))
print(a)
print(a.shape)

a = np.squeeze(a)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(1, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# 전체 차원 축소
# 디폴트값으로 1인 차원 모두 축소
a = np.arange(12).reshape((1,3,1,4))
print(a)
print(a.shape)

a = np.squeeze(a)
print(a)
print(a.shape)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(1, 3, 1, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# 원하는 차원 축소
a = np.arange(12).reshape(1,3,1,4)
print(a)
a = np.squeeze(a,axis=0)
print(a.shape)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(3, 1, 4)


In [ ]:
a = np.arange(12)

# a=a.reshape(3,4)
a = a.reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 전치행렬
a = np.arange(12).reshape(3,4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a = np.arange(12).reshape(3,4)
s = np.sum(a,axis=1)
print(s)

[ 6 22 38]


In [ ]:
# 행렬(0,1)or(n,m)의 각 행별 합계구하기
# axis=1는 행(1)or(m)을 없애줌
# 행렬(0,1)or(n,m)의 각 열별 합계구하기
# axis=0는 열(0)을 없애줌
a = np.arange(15).reshape((5,3))
print(a)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[30 35 40]
[ 3 12 21 30 39]


In [ ]:
# 행렬의 각 행과 열의 평균구하기
a = np.arange(15).reshape((5,3))
print(a)
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[6. 7. 8.]
[ 1.  4.  7. 10. 13.]


In [ ]:
# a를 아래의 shape로 합계구하기
'''
(3, 4)
(4, 5)
(3, 5)
'''

print(np.sum(a,axis=2).shape)
print(np.sum(a,axis=0).shape)
print(np.sum(a,axis=1).shape)


(3, 4)
(4, 5)
(3, 5)


In [ ]:
# 키, 몸무게별 평균 구하기
a = np.array([[170, 65],
            [165, 55],
            [171, 70],
            [155, 50],
            [165, 55]
            ])
print(np.mean(a,axis=0))

[165.2  59. ]


In [ ]:
# argmax는 가장 큰 값의 인덱스를 반환
a = np.array([1,3,5,2,4])
print(np.max(a))
print(np.argmax(a))

5
2


In [ ]:
# 가장 큰 키와 몸무게를 가진 학생들 구하기
# max = 값을 반환
# argmax = 인덱스를 반환
a = np.array([[170, 65],
            [165, 75],
            [171, 70],
            [155, 50],
            [165, 55]
            ])
print(np.max(a,axis=0))
print(np.argmax(a,axis=0))

[171  75]
[2 1]


In [ ]:
a = np.arange(24).reshape(2,3,4)
print(a)
print(np.sum(a,axis=(1,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 66 210]


In [ ]:
a = np.random.rand(12).reshape(4,3)
print(a)

[[0.15037614 0.77821182 0.82979288]
 [0.97932784 0.12876163 0.16967046]
 [0.9971671  0.84986137 0.45022296]
 [0.95730345 0.85350963 0.11460317]]


In [ ]:
# 각 행의 가장 큰값의 인덱스 반환하기
a = np.random.rand(12).reshape(4,3)
print(np.argmax(a, axis=1))

[2 1 0 2]


In [ ]:
# sort
# argsort = sort된 인덱스 반환
a = np.array( [3,7,5,1,8,6,4])
print(np.sort(a))
print(np.argsort(a))

[1 3 4 5 6 7 8]
[3 0 6 2 5 1 4]


- 행합치기 vstack
- 열합치기 hstack

행,열추가와 다름,
새로운 프레임을 만드는 느낌

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [ ]:
c = np.vstack([a,b])
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.arange(12).reshape(3,4)
np.savetxt("my_data.csv",a,delimiter=",")

In [ ]:
b = np.loadtxt("my_data.csv",delimiter=",")
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(b.dtype)

float64


In [ ]:
print(b.astype(np.int))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(6)
print(a)
print(a.astype(np.float))

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]


In [ ]:
names = np.array(["tom","jerry","brute","철수","영희"])
print(names)
heights = np.array([170,177,165,155,175])
print(heights)

# 키순서대로 sort
print(np.sort(heights))
# 키순서대로 인덱스 sort
print(np.argsort(heights))
# 키순서대로 sort한 이름
heights_ordered_index = np.array([3, 2, 0, 4, 1])
print(names[heights_ordered_index])

['tom' 'jerry' 'brute' '철수' '영희']
[170 177 165 155 175]
[155 165 170 175 177]
[3 2 0 4 1]
['철수' 'brute' 'tom' '영희' 'jerry']


In [ ]:
# 안되는 예시
aa = [0,1,2,3,4]

print(aa[3,4,5])

TypeError: ignored

In [ ]:
names = np.array(["tom","jerry","brute","철수","영희"])
print(names)
heights = np.array([170,177,165,155,175])
print(heights)

# 정렬한 인덱스들을 리스트에 할당
print(names[np.argsort(heights)])

['tom' 'jerry' 'brute' '철수' '영희']
[170 177 165 155 175]
['철수' 'brute' 'tom' '영희' 'jerry']


In [ ]:
# 청소순서에 이름 할당하기
# 0 3 4 1 2 ,3,4,1,2,3,4,1,2
i = np.array([0, 3, 4, 1,2,3,4,1,2,3,4,1,2])
print(names[i])

['tom' '철수' '영희' 'jerry' 'brute' '철수' '영희' 'jerry' 'brute' '철수' '영희'
 'jerry' 'brute']


In [ ]:
# 카테고리 인덱스로 인코딩 시키는 법
e = np.eye(5)
print(e[i])

print(names)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['tom' 'jerry' 'brute' '철수' '영희']


In [ ]:
category_indexes = np.array([ 0, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2])
# 카테고리 인덱스로 다시 추출하는법
e = np.eye(5)
one_hot_encoded = e[category_indexes]
predicted = np.argmax(one_hot_encoded, axis=1)
print(predicted)


[0 3 4 1 2 3 4 1 2 3 4 1 2]
