In [8]:
import numpy as np
from sympy import Symbol, solve, Derivative, diff

# 선형대수학 (Linear algebra)

### 리스트
- 데이터형의 혼합가능
- 차원 혼합가능
- 리스트연산 : + (연결), *n (반복)
    
### numpy 배열 = 행열= 매트릭스
- 데이터형의 혼합 x, 한가지 데이터형만 가능
- n 차원인 경우 각 행의 원소수가 같아야함
- 행열 연산

In [2]:
mylist = [ 1, True, '홍길동',4.56]
mylist

[1, True, '홍길동', 4.56]

In [3]:
mylist = [ [1,2,3], [True,False], '홍길동',4.56]
mylist

[[1, 2, 3], [True, False], '홍길동', 4.56]

In [4]:
# 리스트연산 : +
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 10, 20]
list1+list2    # [1, 2, 3, 4, 5, 4, 5, 10, 20]

[1, 2, 3, 4, 5, 4, 5, 10, 20]

In [5]:
# 리스트연산 : *n
list1*3  # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
# numpy 배열 생성
np.array(리스트)

# 속성
- shape : 구조
- size : 길이
- dtype : 데이터형
- ndim :차원

In [9]:
# 1차원
arr1 = np.array([1,2,10,5,9])
# 2차원 = 3*3
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
print(arr1)
arr1

[ 1  2 10  5  9]


array([ 1,  2, 10,  5,  9])

In [12]:
arr1.ndim, # 차원
arr1.shape, # 튜플 반환
arr1.size, # 몇개
arr1.dtype #데이터타입(비트수)

(1, (5,), 5, dtype('int32'))

In [13]:
arr3 = np.array([1,2,10,5,9.5])

In [16]:
arr3.dtype # dtype('float64')

(1, (5,), 5, dtype('float64'))

In [19]:
print(arr2)
arr2.ndim, # 차원
arr2.shape, # 튜플 반환
arr2.size, # 전체개수   # len(list) -> 행수
arr2.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(2, (3, 3), 9, dtype('int32'))

## 초기값지정이 된 넘파이 배열생성

- np.zeros(n) :n개로 구성된 넘파이 배열생성, 값은 모두 0
- np.zeros([n,m]) : n*m개로 구성된 넘파이 배열생성, 값은 모두 0
- np.ones(n) :n개로 구성된 넘파이 배열생성, 값은 모두 1
- np.ones([n,m]) : n*m개로 구성된 넘파이 배열생성, 값은 모두 1
- np.eye(n) : 대각선이 1이고 나머지가 0인 배열생성
- np.tri(n) :대각선이 1이고, 대각선 기준 아래가 1 위가 0인 배열생성
- np.arange(start,end, step) : 순차적인 숫자의 조합으로 배열생성
- np.random.randint(start, end, n) : 정수 난수로 구성된 배열생성

In [20]:
np.zeros(10) # 1차원

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros([2,2])  # 2차원

array([[0., 0.],
       [0., 0.]])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [29]:
# np.arrange(start,end, step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(1,100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [34]:
# reshape(n, m) : 행열구조 변경
# np.arange(1,11).reshape(5,3) -> 오류발생
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
# 난수 배열
# np.random.randint(start, end, n)
np.random.randint(1, 100, 20)

array([44, 93, 58, 82, 79, 97, 58, 41, 90, 80, 44, 90,  6, 66, 76, 90, 58,
        5, 96,  8])

In [36]:
np.random.randint(1, 20, 20).reshape(5,4)

array([[13,  1, 14, 15],
       [ 2, 10, 13,  8],
       [ 4,  6, 11,  5],
       [10, 19,  6, 19],
       [ 1,  3,  9,  9]])

# 넘파이 배열의 연산
- 같은 자리의 데이터끼리 연산

In [44]:
arr1 = np.random.randint(1, 50, 16).reshape(4,4)
arr2 = np.random.randint(1, 50, 16).reshape(4,4)

In [45]:
arr1

array([[11, 45,  7,  3],
       [22, 15, 22, 15],
       [46, 23, 16, 34],
       [43, 28, 12, 24]])

In [46]:
arr2

array([[ 2, 43, 10, 49],
       [ 3, 23, 13,  7],
       [40,  6, 16, 23],
       [29, 35, 47, 35]])

In [47]:
arr1+arr2

array([[13, 88, 17, 52],
       [25, 38, 35, 22],
       [86, 29, 32, 57],
       [72, 63, 59, 59]])

In [49]:
arr1-arr2

array([[  9,   2,  -3, -46],
       [ 19,  -8,   9,   8],
       [  6,  17,   0,  11],
       [ 14,  -7, -35, -11]])

In [48]:
arr1%arr2

array([[ 1,  2,  7,  3],
       [ 1, 15,  9,  1],
       [ 6,  5,  0, 11],
       [14, 28, 12, 24]], dtype=int32)

In [50]:
arr1/arr2

array([[5.5       , 1.04651163, 0.7       , 0.06122449],
       [7.33333333, 0.65217391, 1.69230769, 2.14285714],
       [1.15      , 3.83333333, 1.        , 1.47826087],
       [1.48275862, 0.8       , 0.25531915, 0.68571429]])

In [51]:
arr1//arr2

array([[5, 1, 0, 0],
       [7, 0, 1, 2],
       [1, 3, 1, 1],
       [1, 0, 0, 0]], dtype=int32)

In [52]:
# 전치행열
arr1.T

array([[11, 22, 46, 43],
       [45, 15, 23, 28],
       [ 7, 22, 16, 12],
       [ 3, 15, 34, 24]])

### 행열의 곱 - Dot 연산
- np.dot(행열1, 행열2)

In [54]:
# 2행3열
arr3 = np.random.randint(1,20,6).reshape(2,3)
# 3행2열
arr4 = np.random.randint(1,20,6).reshape(3,2)

In [55]:
arr3

array([[15, 16, 11],
       [12, 13,  6]])

In [56]:
arr4

array([[ 5, 15],
       [14, 13],
       [16, 12]])

In [57]:
np.dot(arr3, arr4)

array([[475, 565],
       [338, 421]])

In [58]:
# 리스트*n
[1,2,3,4,5]*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [59]:
# n을 곱한다
arr4

array([[ 5, 15],
       [14, 13],
       [16, 12]])

In [60]:
arr4*5

array([[25, 75],
       [70, 65],
       [80, 60]])

#  넘파이 배열의 인덱싱과 슬라이싱
- 인덱싱
넘파이배열[row][column]
넘파이배열[row, colnumn]

- 슬라이싱
넘파이배열[start:end:step, start:end:step]

In [ ]:
# 리스트, 딕셔너리, 튜플, 집합
# 집합은 인덱싱, 슬라이싱이 안됨

In [62]:
arr5 = np.random.randint(1,30,25).reshape(5,5)
arr5

array([[ 5, 23,  7, 21, 25],
       [11,  1, 14,  5,  3],
       [27,  1, 21, 29, 29],
       [29,  3, 25,  4, 12],
       [21,  2, 16,  9, 20]])

#### 인덱싱

In [65]:
arr5[0,0], arr5[0][0] # 행의 첫번째, 열의 첫번째

(5, 5)

In [66]:
arr5[-1,-1] # 행의 마지막, 열의 마지막

20

In [67]:
arr5[-2,-3] # 행의 마지막에서 2번째, 열의 마지막에서 3번째

25

#### 슬라이싱  -> 버리고 싶은곳을 선택

In [69]:
# 3행부터 마지막 행까지 출력
arr5[2::,::] # 뒤가 생략이면 끝까지라는 뜻

array([[27,  1, 21, 29, 29],
       [29,  3, 25,  4, 12],
       [21,  2, 16,  9, 20]])

In [70]:
# 3열부터 마지막열까지 출력
arr5[::,2::]

array([[ 7, 21, 25],
       [14,  5,  3],
       [21, 29, 29],
       [25,  4, 12],
       [16,  9, 20]])

In [71]:
# 행과 열을 같이 슬라이싱
arr5[1:3:,2::]

array([[14,  5,  3],
       [21, 29, 29]])

In [72]:
# 짝수번째 행 출력
arr5[1::2,::]

array([[11,  1, 14,  5,  3],
       [29,  3, 25,  4, 12]])